 // Mock data for papers - in a real application, this would come from an API
  export const papers = [
    {
      id: 1,
      title: "Computer Science Fundamentals",
      year: "2023",
      subject: "Computer Science",
      downloadLink: "#",
    },
    {
      id: 2,
      title: "Data Structures and Algorithms",
      year: "2023",
      subject: "Computer Science",
      downloadLink: "#",
    },
    {
      id: 3,
      title: "Mathematics for Machine Learning",
      year: "2023",
      subject: "Mathematics",
      downloadLink: "#",
    },
    {
      id: 4,
      title: "Physics Mechanics",
      year: "2023",
      subject: "Physics",
      downloadLink: "#",
    },
    {
      id: 5,
      title: "Organic Chemistry",
      year: "2023",
      subject: "Chemistry",
      downloadLink: "#",
    },
    {
      id: 6,
      title: "Molecular Biology",
      year: "2023",
      subject: "Biology",
      downloadLink: "#",
    },
      {
      id: 3,
      title: "Mathematics for Machine Learning",
      year: "2023",
      subject: "Mathematics",
      downloadLink: "#",
    },
    {
      id: 4,
      title: "Physics Mechanics",
      year: "2023",
      subject: "Physics",
      downloadLink: "#",
    },
    {
      id: 5,
      title: "Organic Chemistry",
      year: "2023",
      subject: "Chemistry",
      downloadLink: "#",
    },
    {
      id: 6,
      title: "Molecular Biology",
      year: "2023",
      subject: "Biology",
      downloadLink: "#",
    },
      {
      id: 3,
      title: "Mathematics for Machine Learning",
      year: "2023",
      subject: "Mathematics",
      downloadLink: "#",
    },
    {
      id: 4,
      title: "Physics Mechanics",
      year: "2023",
      subject: "Physics",
      downloadLink: "#",
    },
    {
      id: 5,
      title: "Organic Chemistry",
      year: "2023",
      subject: "Chemistry",
      downloadLink: "#",
    },
    {
      id: 6,
      title: "Molecular Biology",
      year: "2023",
      subject: "Biology",
      downloadLink: "#",
    },
      {
      id: 3,
      title: "Mathematics for Machine Learning",
      year: "2023",
      subject: "Mathematics",
      downloadLink: "#",
    },
    {
      id: 4,
      title: "Physics Mechanics",
      year: "2023",
      subject: "Physics",
      downloadLink: "#",
    },
    {
      id: 5,
      title: "Organic Chemistry",
      year: "2023",
      subject: "Chemistry",
      downloadLink: "#",
    },
    {
      id: 6,
      title: "Molecular Biology",
      year: "2023",
      subject: "Biology",
      downloadLink: "#",
    },
  ];
